name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.0

    - name: Terraform Init
      run: terraform init terraform/

    - name: Terraform Plan
      run: terraform plan -out=tfplan terraform/

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    - name: Set up Ansible
      run: |
        sudo apt-get install -y ansible

    - name: Get VM Public IP
      id: get_ip
      run: |
        echo "::set-output name=public_ip::$(terraform output -json | jq -r '.public_ip.value')"

    - name: Run Ansible Playbook
      run: ansible-playbook ansible/deploy_app.yml -i "${{ steps.get_ip.outputs.public_ip }}," --user azureuser --private-key <path_to_your_private_key>
