name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      RESOURCE_GROUP_NAME: "Network-latest-10"
      ADMIN_USERNAME: "azureuser"
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Initialize Terraform
        run: terraform init

      # Specify the directory that contains the Terraform configuration files
      - name: Import Network Security Group into Terraform State
        run: |
          cd terraform  # Change to the directory where Terraform files are located
          terraform import azurerm_network_security_group.nsg "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP_NAME }}/providers/Microsoft.Network/networkSecurityGroups/Network-NSG"

      # Apply the Terraform configuration to ensure the state is up-to-date
      - name: Apply Terraform Configuration
        run: |
          cd terraform  # Ensure you are in the correct directory
          terraform apply -auto-approve

      # Show Terraform state after the import
      - name: Show Terraform State after Import
        run: |
          cd terraform  # Ensure you are in the correct directory
          terraform state list
